- name: Cloud Computing
  weight: 5

- name: Docker
  weight: 5

- name: Hyper-V
  weight: 3

- name: VMware VSphere
  weight: 4

- name: Proxmox
  weight: 5

- name: Debian/Ubuntu
  weight: 5

- name: Windows 3.11 - Windows 11
  weight: 4

- name:  Windows Server 2003-20xx
  weight: 4

- name:  Kubernetes
  weight: 3
